Repository WildCodeSchool/2022-09-JS-TLSE-MakeSense, pull requests merged in 2023-01, with the labels that each got.

#44 Group management
  backend/src/controllers/groupsControllers.js
  backend/src/midleware/Password.js
  backend/src/models/GroupsManager.js
  backend/src/router.js
  frontend/src/components/container/Admin/GroupsManager.jsx
  frontend/src/components/container/Admin/Languages.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsAll.jsx
  frontend/src/components/header/AppBar.jsx
  frontend/src/components/header/LanguageSelector.jsx
  frontend/src/contexts/useAuth.jsx
Labels: Conflicts, Corrections done

#47 sorry sorry sorry
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/services/api.js
Labels: Reviewed

#48 Modify user by admin
  frontend/src/components/container/Admin/UsersManager.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/components/container/Protected/Decisions/form/Concerned.jsx
  frontend/src/components/header/CommentSection.jsx
Labels: Corrections done

#49 Traduction branche
  backend/package-lock.json
  frontend/package-lock.json
  frontend/src/assets/css/App.scss
  frontend/src/assets/css/Layout.scss
  frontend/src/assets/css/header/AppBar.scss
  frontend/src/assets/img/photo-connexion.svg
  frontend/src/components/AdminLayout.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/components/container/Protected/Decisions/form/Concerned.jsx
Labels: Reviewed

#50 Group management
  frontend/src/components/container/Admin/Decisions.jsx
  frontend/src/components/container/Admin/GroupsManager.jsx
  frontend/src/components/container/Admin/Languages.jsx
  frontend/src/contexts/functions/ReconnectApi.js
  frontend/src/contexts/useAuth.jsx
  frontend/src/pages/Protected/Profile.jsx
Labels: Reviewed

#51 add buttons in my decisions page
  frontend/src/components/Spinner.jsx
  frontend/src/components/container/Admin/GroupsManager.jsx
  frontend/src/components/container/Admin/Languages.jsx
  frontend/src/components/container/Admin/UsersManager.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsUser.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserDecisions.jsx
  frontend/src/components/header/AppBar.jsx
Labels: Corrections done

#52 Modif decisions
  frontend/package-lock.json
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
Labels: Reviewed

#54 in decision page, add decisions where impacted and comments
  backend/src/controllers/decisionsControllers.js
  backend/src/models/DecisionsManager.js
  backend/src/models/ExpertsManager.js
  backend/src/models/ImpactedManager.js
  frontend/src/components/container/Protected/Decisions/Card.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsAll.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsUser.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserComment.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserConcerned.jsx
Labels: Conflicts

#55 Traduction branche
  frontend/src/components/container/Admin/Decisions.jsx
  frontend/src/components/container/Admin/GroupsManager.jsx
  frontend/src/components/container/Admin/Languages.jsx
  frontend/src/components/container/ErrorPage.jsx
  frontend/src/components/container/Protected/Decisions/Card.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsAll.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsUser.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserDecisions.jsx
  frontend/src/components/footer/FooterBar.jsx
  frontend/src/components/header/AppBar.jsx
  frontend/src/components/header/CommentSection.jsx
  frontend/src/components/header/Comments.jsx
Labels: Reviewed

#56 Group management
  .github/workflows/deploy-back.yml
  .github/workflows/deploy-front.yml
  README.md
  backend/Dockerfile
  backend/src/controllers/commentsControllers.js
  backend/src/controllers/decisionsControllers.js
  backend/src/controllers/expertsControllers.js
  backend/src/controllers/groupsControllers.js
  backend/src/controllers/impactedControllers.js
  backend/src/models/CommentsManager.js
  backend/src/models/DecisionsManager.js
  backend/src/models/ExpertsManager.js
  backend/src/models/GroupsManager.js
  backend/src/models/ImpactedManager.js
  backend/src/router.js
  captain-definition-backend
  captain-definition-frontend
  frontend/Dockerfile
  frontend/default.conf
  frontend/src/App.jsx
  frontend/src/components/container/Admin/GroupsManager.jsx
  frontend/src/components/container/Protected/Decisions/CommentSection.jsx
  frontend/src/components/container/Protected/Decisions/Comments.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/components/container/Protected/Decisions/Pagination.jsx
  frontend/src/contexts/useAuth.jsx
Labels: Reviewed, Conflicts

#57 post groups impacted and experts when submit form
  backend/src/controllers/decisionsControllers.js
  backend/src/models/DecisionsManager.js
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/pages/Home/Login.jsx
  frontend/src/pages/Home/Register.jsx
Labels: Reviewed

#58 show groups impacted and experts on decision page
  backend/src/controllers/groupsControllers.js
  backend/src/models/GroupsManager.js
  backend/src/router.js
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
Labels: Reviewed

#60 Traduction branche
  frontend/src/components/container/Admin/Dashboard.jsx
  frontend/src/components/container/Admin/GroupsManager.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsAll.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserDecisions.jsx
  frontend/src/components/header/AppBar.jsx
  frontend/src/pages/Protected/Profile.jsx
Labels: Reviewed

#61 user can see all decisions by category
  backend/src/controllers/decisionsControllers.js
  backend/src/models/DecisionsManager.js
  frontend/src/components/container/Admin/GroupsManager.jsx
  frontend/src/components/container/Protected/Decisions/Card.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsUser.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserConcerned.jsx
  frontend/src/contexts/useAuth.jsx
  frontend/src/services/api.js
Labels: Reviewed

#63 Correction code cassé: envoi modif décisions dans la BDD fonctionnel
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
Labels: Reviewed

#64 Change nav bar
  frontend/src/components/container/Protected/Decisions/DecisionsAll.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsProfil.jsx
  frontend/src/components/container/Protected/Decisions/ShowAllDecisions.jsx
  frontend/src/components/header/AppBar.jsx
Labels: Reviewed

#67 fix bugs
  backend/src/models/DecisionsManager.js
  frontend/src/components/container/Admin/AdminBar.jsx
  frontend/src/components/container/Admin/Decisions.jsx
  frontend/src/components/container/Admin/Groupes.jsx
  frontend/src/components/container/Admin/Languages.jsx
  frontend/src/components/container/Admin/Register.jsx
  frontend/src/components/container/Admin/Utilisateurs.jsx
  frontend/src/components/container/Protected/Decisions/CommentSection.jsx
  frontend/src/components/container/Protected/Decisions/Comments.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsAll.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsPage.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsUser.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserConcerned.jsx
  frontend/src/components/header/AppBar.jsx
  frontend/src/pages/Home/Login.jsx
  frontend/src/pages/Home/Register.jsx
  frontend/src/pages/Protected/Profile.jsx
Labels: Reviewed

#68 graphique
  frontend/src/components/container/Admin/Dashboard.jsx
Labels: Corrections done

#69 add style on edit form
  frontend/src/assets/css/container/admin/Dashboard.scss
  frontend/src/components/container/Admin/Dashboard.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsForm.jsx
  frontend/src/components/header/AppBar.jsx
Labels: Reviewed

#70 update database
  backend/database.sql
  frontend/src/assets/css/container/admin/Dashboard.scss
  frontend/src/components/container/Admin/Dashboard.jsx
  frontend/src/components/container/Protected/Decisions/DecisionsAll.jsx
  frontend/src/components/container/Protected/Decisions/ShowUserConcerned.jsx
  frontend/src/pages/Protected/Profile.jsx
Labels: Reviewed

#72 add modal when edit form
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
Labels: Reviewed

#73 Dev
  frontend/src/components/container/Protected/Decisions/DecisionsEdit.jsx
Labels: Reviewed
